import {exercises,workouts,weekKey,createState,current,updateLoad,complete,undo,migrateState,exerciseRecord,toggleExercise} from './model.js';
const KEY='meus-treinos-v1';
const app=document.querySelector('#app');
const message=document.querySelector('#message');
const fmt=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2});
const dateFmt=new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,area='training',selected='leg',editing=null,loaded=true;
let selectedDay=(workouts.find(w=>w.number===new Date().getDay())||workouts[0]).id;
function notify(text){message.textContent=text;clearTimeout(notify.timer);notify.timer=setTimeout(()=>message.textContent='',5000);}
try {const saved=localStorage.getItem(KEY);state=saved?JSON.parse(saved):createState();if(state.version!==1||!state.history||!Array.isArray(state.sessions))throw Error();for(const e of Object.values(exercises).filter(e=>e.loads)){if(!state.history[e.id])state.history[e.id]=[{date:new Date().toISOString(),loads:[...e.loads],kind:'initial'}];if(!Array.isArray(state.history[e.id])||!state.history[e.id].length||state.history[e.id].some(h=>!Array.isArray(h.loads)||h.loads.length!==e.loads.length||h.loads.some(n=>typeof n!=='number'||!Number.isFinite(n)||n<0)||!Number.isFinite(Date.parse(h.date))))throw Error();}const needsMigration=!state.exerciseRecords;migrateState(state);if(!saved||needsMigration)localStorage.setItem(KEY,JSON.stringify(state));}
catch {loaded=false;app.innerHTML='<div class="empty"><h1>Dados indisponíveis</h1><p>Não foi possível ler ou gravar os dados locais. Os dados existentes não foram substituídos. Verifique se o armazenamento do navegador está disponível.</p></div>';}
function change(action){const next=structuredClone(state);try{action(next);localStorage.setItem(KEY,JSON.stringify(next));state=next;editing=null;render();return true;}catch(e){notify(e.message||'Não foi possível salvar.');return false;}}
function loadText(loads,id){return loads.map(n=>fmt.format(n)).join(' / ')+' '+exercises[id].unit;}
function session(w){return state.sessions.findLast(s=>s.week===weekKey()&&s.workout===w.id&&!s.undone);}
function row(id,w){
 const ex=exercises[id],record=exerciseRecord(state,w,id),done=!!record;
 const name=w.names?.[id]||ex?.name||'Cardio';
 const loads=record?.loads??current(state,id,w),initial=w.initial?.[id];
 const choiceKey=weekKey()+':'+w.id+':'+id;
 const chosen=record?.selection??state.selections?.[choiceKey]??0;
 const action=`<button class="exercise-status" data-toggle="${w.id}:${id}" aria-label="${done?'Desfazer conclusão de':'Marcar como feito'} ${esc(name)}" aria-pressed="${done}">${done?'DESFAZER':'FEITO'}</button>`;
 return `<div class="row ${done?'exercise-done':''}" data-exercise-row="${w.id}:${id}"><div class="exercise"><strong>${esc(name)}</strong>${ex?.labels.length?`<small>${ex.labels.join(' / ')}</small>`:''}${initial?`<small>Carga informada para ${w.day.toLowerCase()}: ${loadText(initial,id)}</small>`:''}${record?`<small>Feito em ${dateFmt.format(new Date(record.date))}</small>`:''}</div><div class="row-actions">${!ex?`<span class="plain">${w.minutes?`${w.minutes} min`:''}</span>`:!ex.loads?'<span class="plain">Peso corporal</span>':done?`<span class="plain used-load">${loadText(loads,id)}</span>`:`<button class="weight" data-edit="${w.id}:${id}" aria-label="Editar carga de ${esc(name)}">${loadText(loads,id)} · Editar</button>`}${action}</div>${ex?.labels.length?`<div class="options" role="group" aria-label="Alternativa utilizada">${ex.labels.map((label,i)=>done?(chosen===i?`<small>Realizado: ${label} · ${fmt.format(loads[i])} kg</small>`:''):`<label><input type="radio" name="${w.id}-${id}" data-choice="${choiceKey}" value="${i}" ${chosen===i?'checked':''}> ${label}</label>`).join('')}</div>`:''}${editing===`${w.id}:${id}`&&!done?`<form class="editor" data-workout="${w.id}" data-exercise="${id}">${loads.map((n,i)=>`<label>${ex.labels[i]||ex.unit}<input name="load${i}" type="number" min="0" step="any" required inputmode="decimal" value="${n}" aria-label="${esc(name)} ${ex.labels[i]||'carga'}"></label>`).join('')}<button class="primary" type="submit">Salvar</button><button type="button" data-cancel>Cancelar</button><p class="error" role="alert"></p></form>`:''}</div>`;
}
function card(w){
 const s=session(w),today=new Date().getDay()===w.number;
 const pending=w.items.filter(id=>!exerciseRecord(state,w,id)),done=w.items.filter(id=>exerciseRecord(state,w,id));
 return `<article class="card ${s?'done':''} ${today&&!s?'today':''}" id="${w.id}"><div class="card-head"><div><h2>${w.day.toUpperCase()}${today?' · HOJE':''}</h2><p>${w.items.length} exercícios · ${w.reps}</p><p class="exercise-counter">${done.length} de ${w.items.length} exercícios feitos</p>${s?`<p>Concluído em ${dateFmt.format(new Date(s.date))}</p>`:''}</div><span class="badge">${s?'FEITO':'PENDENTE'}</span></div>${pending.length?`<h3 class="exercise-section">PENDENTES</h3>${pending.map(id=>row(id,w)).join('')}`:''}${done.length?`<h3 class="exercise-section">FEITOS</h3>${done.map(id=>row(id,w)).join('')}`:''}<div class="card-foot">${s?`<button data-undo="${s.id}" style="width:100%">Desfazer conclusão</button>`:`<button class="primary" data-complete="${w.id}">Marcar como feito</button>`}</div></article>`;
}
function training(){
 const done=workouts.filter(w=>session(w));
 const monday=new Date(weekKey()+'T12:00:00'),sunday=new Date(monday);
 sunday.setDate(sunday.getDate()+6);
 const short=d=>d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});
 app.innerHTML=`<div class="intro"><h1>TREINOS</h1><p>${short(monday)} — ${short(sunday)} · ${monday.getFullYear()}</p><div class="summary"><span>${6-done.length} pendentes</span><span>${done.length} de 6 feitos</span></div></div><div class="training-days"><div class="day-tabs" role="group" aria-label="Dias de treino">${workouts.map((w,i)=>`<button id="day-${w.id}" data-day="${w.id}" aria-pressed="${w.id===selectedDay}" aria-controls="day-content" aria-label="${w.day}: ${session(w)?'feito':'pendente'}">${['SEG','TER','QUA','QUI','SEX','SÁB'][i]}<span class="day-indicator ${session(w)?'is-done':''}" aria-hidden="true"></span></button>`).join('')}</div><div id="day-content" role="region" aria-labelledby="day-${selectedDay}">${card(workouts.find(w=>w.id===selectedDay))}</div></div>`;
}
function chart(history,ex){const W=700,H=260,left=50,right=20,top=20,bottom=45;const vals=history.flatMap(h=>h.loads),lo=Math.max(0,Math.min(...vals)-5),hi=Math.max(...vals)+5;const first=Date.parse(history[0].date),last=Date.parse(history.at(-1).date);const x=(h,i)=>last===first?left+(W-left-right)*(history.length===1?.5:i/(history.length-1)):left+(W-left-right)*(Date.parse(h.date)-first)/(last-first);const y=n=>top+(H-top-bottom)*(1-(n-lo)/(hi-lo));const lines=Array.from({length:4},(_,i)=>{const n=lo+(hi-lo)*i/3;return `<line x1="${left}" x2="${W-right}" y1="${y(n)}" y2="${y(n)}" stroke="#292929"/><text x="${left-9}" y="${y(n)+4}" text-anchor="end">${fmt.format(n)}</text>`;}).join('');return `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Evolução da carga em quilogramas. Valores detalhados no histórico abaixo.">${lines}${ex.loads.map((_,j)=>`<polyline fill="none" stroke="${j?'#D3D3D3':'#BA55D3'}" stroke-width="3" points="${history.map((h,i)=>`${x(h,i)},${y(h.loads[j])}`).join(' ')}"/>${history.map((h,i)=>`<circle cx="${x(h,i)}" cy="${y(h.loads[j])}" r="4" fill="${j?'#D3D3D3':'#BA55D3'}"><title>${new Date(h.date).toLocaleDateString('pt-BR')}: ${loadText(h.loads,ex.id)}</title></circle>`).join('')}`).join('')}<text x="${left}" y="${H-10}">${new Date(first).toLocaleDateString('pt-BR')}</text><text x="${W-right}" y="${H-10}" text-anchor="end">${history.length>1?new Date(last).toLocaleDateString('pt-BR'):''}</text></svg>`;}
function progress(){const ex=exercises[selected],h=state.history[selected],initial=h[0].loads,latest=h.at(-1).loads,max=latest.map((_,i)=>Math.max(...h.map(r=>r.loads[i]))),diff=latest.map((n,i)=>n-initial[i]);const stat=(label,v)=>`<div class="stat"><span>${label}</span><strong>${v}</strong></div>`;app.innerHTML=`<div class="intro"><span class="eyebrow">HISTÓRICO DE CARGAS</span><h1>PROGRESSÃO</h1><p>O histórico de carga acompanha o exercício, em todos os dias.</p></div><label class="selector">Exercício<select id="exercise-select">${Object.values(exercises).filter(e=>e.loads).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')).map(e=>`<option value="${e.id}" ${e.id===selected?'selected':''}>${esc(e.name)}</option>`).join('')}</select></label><h2>${esc(ex.name)}</h2>${ex.labels.length?`<p>Valores na ordem: ${ex.labels.join(' / ')}</p>`:''}<div class="stats">${stat('Carga inicial',loadText(initial,selected))}${stat('Carga atual',loadText(latest,selected))}${stat('Maior carga',loadText(max,selected))}${stat('Evolução',diff.map(n=>(n>0?'+':'')+fmt.format(n)).join(' / ')+' '+ex.unit)}</div><section class="panel"><h3>EVOLUÇÃO DE CARGA</h3><p>Carga (${ex.unit}) · Data</p>${chart(h,ex)}${ex.labels.length?`<div class="legend">${ex.labels.map((label,i)=>`<span style="color:${i?'#D3D3D3':'#d79ae7'}">${label}</span>`).join('')}</div>`:''}</section><section class="panel"><h3>HISTÓRICO</h3><ul class="history">${h.map(r=>`<li><span>${dateFmt.format(new Date(r.date))}<small>${r.kind==='initial'?'Carga inicial registrada':r.kind==='prescription'?'Carga anterior informada para o dia':'Carga alterada'}</small></span><strong>${loadText(r.loads,selected)}</strong></li>`).join('')}</ul></section>`;}
function render(){if(!loaded)return;document.querySelector('#training-tab').setAttribute('aria-pressed',area==='training');document.querySelector('#progress-tab').setAttribute('aria-pressed',area==='progress');area==='training'?training():progress();}
for(const [id,value] of [['training-tab','training'],['progress-tab','progress']])document.getElementById(id).onclick=()=>{area=value;editing=null;render();};
app.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.day){selectedDay=b.dataset.day;editing=null;render();document.getElementById('day-'+selectedDay)?.focus();}if(b.dataset.toggle){const [workout,id]=b.dataset.toggle.split(':');change(s=>toggleExercise(s,workouts.find(w=>w.id===workout),id));}if(b.dataset.edit){editing=b.dataset.edit;render();app.querySelector('.editor input')?.focus();}if(b.hasAttribute('data-cancel')){editing=null;render();}if(b.dataset.complete){if(change(s=>complete(s,workouts.find(w=>w.id===b.dataset.complete))))notify('Treino concluído. Cargas registradas.');}if(b.dataset.undo){if(change(s=>undo(s,b.dataset.undo)))notify('Conclusão desfeita. Registro preservado.');}});
app.addEventListener('submit',event=>{event.preventDefault();const f=event.target,id=f.dataset.exercise;const loads=exercises[id].loads.map((_,i)=>Number(f.elements[`load${i}`].value));if(change(s=>updateLoad(s,id,loads,new Date().toISOString(),current(s,id,workouts.find(w=>w.id===f.dataset.workout)))))notify('Carga salva no histórico.');});
app.addEventListener('change',event=>{if(event.target.dataset?.choice){const key=event.target.dataset.choice;const value=Number(event.target.value);change(s=>{s.selections??={};s.selections[key]=value;});}if(event.target.id==='exercise-select'){selected=event.target.value;render();}});
// ponytail: dados ficam neste navegador; sincronização requer persistência compartilhada.
window.addEventListener('storage',event=>{if(event.key===KEY){location.reload();}});
let displayedWeek=weekKey();setInterval(()=>{if(weekKey()!==displayedWeek){displayedWeek=weekKey();render();}},30000);
render();

