import {test} from 'node:test';
import assert from 'node:assert/strict';
import {workouts,createState,current,updateLoad,complete,undo,weekKey,migrateState,exerciseRecord,toggleExercise} from './model.js';
test('cargas, equivalências, alternativas, conclusão, desfazer e virada da semana',()=>{
 const s=createState('2026-09-14T12:00:00.000Z');
 assert.deepEqual(workouts.map(w=>w.items.length),[12,11,9,10,11,9]);
 assert.deepEqual(current(s,'adu',workouts[3]),[40]);
 assert.deepEqual(current(s,'coice',workouts[3]),[70]);
 updateLoad(s,'leg',[110],'2026-09-16T12:00:00.000Z');
 assert.deepEqual(current(s,'leg',workouts[3]),[110]);
 assert.deepEqual(s.history.leg.map(h=>h.loads[0]),[100,110]);
 for(const invalid of [[-1],[NaN],[Infinity],[],['10']])assert.throws(()=>updateLoad(s,'leg',invalid));
 assert.deepEqual(current(s,'dev'),[10,3]);
 updateLoad(s,'dev',[12,4]);assert.equal(s.history.dev.length,2);
 const day=new Date(2026,8,17,12);complete(s,workouts[0],day);complete(s,workouts[0],day);assert.equal(s.sessions.length,1);
 updateLoad(s,'leg',[120]);assert.deepEqual(s.sessions[0].loads.leg,[110]);
 const reloaded=JSON.parse(JSON.stringify(s));assert.deepEqual(current(reloaded,'leg'),[120]);
 assert.equal(weekKey(new Date(2026,8,20,23,59)),'2026-09-14');
 assert.equal(weekKey(new Date(2026,8,21,0,0)),'2026-09-21');
 complete(s,workouts[0],new Date(2026,8,21,12));assert.equal(s.sessions.length,2);
 undo(s,s.sessions[0].id);assert.ok(s.sessions[0].undone);assert.deepEqual(s.sessions[0].loads.leg,[110]);
 assert.equal(s.history.leg.length,3);
 updateLoad(s,'coice',[75],undefined,current(s,'coice',workouts[3]));assert.deepEqual(s.history.coice.map(h=>h.loads[0]),[40,70,75]);
 updateLoad(s,'stiff',[10,35]);assert.deepEqual(current(s,'mesa'),[35]);updateLoad(s,'mesa',[40]);assert.deepEqual(current(s,'stiff'),[10,40]);
});
test('individual, conclusao automatica, migracao e semanas',()=>{
 const day=new Date(2026,8,17,12),next=new Date(2026,8,21,12),w=workouts[0],s=createState();
 const originalHistory=JSON.stringify(s.history);
 toggleExercise(s,w,'leg',day);
 assert.ok(exerciseRecord(s,w,'leg',day));assert.equal(exerciseRecord(s,workouts[3],'leg',day),undefined);
 assert.equal(s.sessions.length,0);assert.equal(JSON.stringify(s.history),originalHistory);
 toggleExercise(s,w,'leg',day);assert.equal(exerciseRecord(s,w,'leg',day),undefined);
 toggleExercise(s,w,'leg',day);updateLoad(s,'leg',[125]);
 for(const id of w.items.slice(1))toggleExercise(s,w,id,day);
 assert.equal(s.sessions.length,1);assert.deepEqual(s.sessions[0].loads.leg,[100]);
 const history=JSON.stringify(s.history);
 toggleExercise(s,w,'pant',day);assert.ok(s.sessions[0].undone);assert.ok(exerciseRecord(s,w,'leg',day));assert.equal(exerciseRecord(s,w,'pant',day),undefined);
 toggleExercise(s,w,'pant',day);assert.equal(s.sessions.length,2);
 assert.equal(JSON.stringify(s.history),history);
 assert.equal(exerciseRecord(s,w,'leg',next),undefined);assert.deepEqual(current(s,'leg'),[125]);
 const legacy=JSON.parse(JSON.stringify(s));delete legacy.exerciseRecords;
 const sessions=JSON.stringify(legacy.sessions),loads=JSON.stringify(legacy.history);
 migrateState(legacy);assert.equal(JSON.stringify(legacy.sessions),sessions);assert.equal(JSON.stringify(legacy.history),loads);assert.ok(exerciseRecord(legacy,w,'leg',day));
 const count=legacy.exerciseRecords.length;migrateState(legacy);assert.equal(legacy.exerciseRecords.length,count);
 complete(s,workouts[2],day);assert.ok(exerciseRecord(s,workouts[2],'cardio',day));assert.ok(exerciseRecord(s,workouts[2],'flex',day));
 undo(s,s.sessions.at(-1).id);assert.equal(exerciseRecord(s,workouts[2],'cardio',day),undefined);
});
test('interface: edição, persistência, conclusão, desfazer e gráfico',async()=>{
 const listeners={},nodes={};
 for(const id of ['#app','#message','#training-tab','#progress-tab'])nodes[id]={innerHTML:'',textContent:'',setAttribute(){},addEventListener(name,fn){listeners[name]=fn;},querySelector(){return {focus(){}};}};
 globalThis.document={querySelector:id=>nodes[id],getElementById:id=>nodes['#'+id]};
 const store=new Map();globalThis.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v)};
 globalThis.window={addEventListener(){}};
 const oldInterval=globalThis.setInterval;globalThis.setInterval=()=>0;
 const oldTimeout=globalThis.setTimeout;globalThis.setTimeout=()=>0;
 try {
 await import('./app.js');
 assert.match(nodes['#app'].innerHTML,/TREINOS DA SEMANA/);
 const click=dataset=>listeners.click({target:{closest:()=>({dataset,hasAttribute:()=>false})}});
 const segment=()=>nodes['#app'].innerHTML.match(/<article[^>]*id="seg">([\s\S]*?)<\/article>/)[1];
 click({toggle:'seg:leg'});
 assert.ok(segment().indexOf('data-exercise-row="seg:pant"')<segment().indexOf('data-exercise-row="seg:leg"'));
 assert.match(segment(),/1 de 12/);assert.match(segment(),/exercise-section">FEITOS/);
 const historyBefore=JSON.stringify(JSON.parse(store.get('meus-treinos-v1')).history);
 await import('./app.js?reload=1');assert.match(segment(),/1 de 12/);assert.match(segment(),/DESFAZER/);
 click({toggle:'seg:leg'});assert.match(segment(),/0 de 12/);
 assert.ok(segment().indexOf('data-exercise-row="seg:leg"')<segment().indexOf('data-exercise-row="seg:pant"'));
 assert.equal(JSON.stringify(JSON.parse(store.get('meus-treinos-v1')).history),historyBefore);
 click({edit:'seg:leg'});assert.match(nodes['#app'].innerHTML,/class="editor"/);
 listeners.submit({preventDefault(){},target:{dataset:{exercise:'leg',workout:'seg'},elements:{load0:{value:'115'}}}});
 assert.equal(JSON.parse(store.get('meus-treinos-v1')).history.leg.at(-1).loads[0],115);
 click({complete:'seg'});let saved=JSON.parse(store.get('meus-treinos-v1'));assert.equal(saved.sessions.length,1);assert.match(nodes['#app'].innerHTML,/Desfazer conclusão/);
 click({undo:saved.sessions[0].id});assert.ok(JSON.parse(store.get('meus-treinos-v1')).sessions[0].undone);
 listeners.change({target:{dataset:{choice:weekKey()+':ter:dev'},value:'1'}});click({complete:'ter'});assert.equal(JSON.parse(store.get('meus-treinos-v1')).sessions.at(-1).selections.dev,1);
 const preserved=store.get('meus-treinos-v1');const normalSet=localStorage.setItem;localStorage.setItem=()=>{throw Error('Armazenamento cheio');};click({complete:'qua'});assert.equal(store.get('meus-treinos-v1'),preserved);assert.equal(nodes['#message'].textContent,'Armazenamento cheio');localStorage.setItem=normalSet;
 nodes['#progress-tab'].onclick();assert.match(nodes['#app'].innerHTML,/<svg/);assert.match(nodes['#app'].innerHTML,/115 kg/);
 nodes['#training-tab'].onclick();
 for(const id of workouts[3].items)click({toggle:'qui:'+id});
 assert.equal(JSON.parse(store.get('meus-treinos-v1')).sessions.filter(s=>s.workout==='qui'&&!s.undone).length,1);
 click({toggle:'qui:leg'});assert.equal(JSON.parse(store.get('meus-treinos-v1')).sessions.filter(s=>s.workout==='qui'&&!s.undone).length,0);
 nodes['#progress-tab'].onclick();
 listeners.change({target:{id:'exercise-select',value:'dev'}});assert.match(nodes['#app'].innerHTML,/Máquina \/ Halter/);
 }finally{globalThis.setInterval=oldInterval;globalThis.setTimeout=oldTimeout;}
});
