import {test} from 'node:test';
import assert from 'node:assert/strict';
import {exerciseCatalog,workoutPlan,saveExercise,deleteExercise,workouts,createState,current,updateLoad,complete,undo,weekKey,migrateState,exerciseRecord,toggleExercise} from './model.js';
test('cargas, equivalências, alternativas, conclusão, desfazer e virada da semana',()=>{
 const s=createState('2026-09-14T12:00:00.000Z');
 assert.deepEqual(workouts.map(w=>w.items.length),[12,11,9,10,11,9]);
 assert.deepEqual(current(s,'adu',workouts[3]),[40]);
 assert.deepEqual(current(s,'coice',workouts[3]),[70]);
 updateLoad(s,'leg',[110],'2026-09-16T12:00:00.000Z');
 assert.deepEqual(current(s,'leg',workouts[3]),[110]);
 assert.deepEqual(s.history.leg.map(h=>h.loads[0]),[100,110]);
 for(const invalid of [[-1],[NaN],[Infinity],[],['10']])assert.throws(()=>updateLoad(s,'leg',invalid));
 assert.deepEqual(current(s,'dev'),[10,3]);
 updateLoad(s,'dev',[12,4]);assert.equal(s.history.dev.length,2);
 const day=new Date(2026,8,17,12);complete(s,workouts[0],day);complete(s,workouts[0],day);assert.equal(s.sessions.length,1);
 updateLoad(s,'leg',[120]);assert.deepEqual(s.sessions[0].loads.leg,[110]);
 const reloaded=JSON.parse(JSON.stringify(s));assert.deepEqual(current(reloaded,'leg'),[120]);
 assert.equal(weekKey(new Date(2026,8,20,23,59)),'2026-09-14');
 assert.equal(weekKey(new Date(2026,8,21,0,0)),'2026-09-21');
 complete(s,workouts[0],new Date(2026,8,21,12));assert.equal(s.sessions.length,2);
 undo(s,s.sessions[0].id);assert.ok(s.sessions[0].undone);assert.deepEqual(s.sessions[0].loads.leg,[110]);
 assert.equal(s.history.leg.length,3);
 updateLoad(s,'coice',[75],undefined,current(s,'coice',workouts[3]));assert.deepEqual(s.history.coice.map(h=>h.loads[0]),[40,70,75]);
 updateLoad(s,'stiff',[10,35]);assert.deepEqual(current(s,'mesa'),[35]);updateLoad(s,'mesa',[40]);assert.deepEqual(current(s,'stiff'),[10,40]);
});
test('individual, conclusao automatica, migracao e semanas',()=>{
 const day=new Date(2026,8,17,12),next=new Date(2026,8,21,12),w=workouts[0],s=createState();
 const originalHistory=JSON.stringify(s.history);
 toggleExercise(s,w,'leg',day);
 assert.ok(exerciseRecord(s,w,'leg',day));assert.equal(exerciseRecord(s,workouts[3],'leg',day),undefined);
 assert.equal(s.sessions.length,0);assert.equal(JSON.stringify(s.history),originalHistory);
 toggleExercise(s,w,'leg',day);assert.equal(exerciseRecord(s,w,'leg',day),undefined);
 toggleExercise(s,w,'leg',day);updateLoad(s,'leg',[125]);
 for(const id of w.items.slice(1))toggleExercise(s,w,id,day);
 assert.equal(s.sessions.length,1);assert.deepEqual(s.sessions[0].loads.leg,[100]);
 const history=JSON.stringify(s.history);
 toggleExercise(s,w,'pant',day);assert.ok(s.sessions[0].undone);assert.ok(exerciseRecord(s,w,'leg',day));assert.equal(exerciseRecord(s,w,'pant',day),undefined);
 toggleExercise(s,w,'pant',day);assert.equal(s.sessions.length,2);
 assert.equal(JSON.stringify(s.history),history);
 assert.equal(exerciseRecord(s,w,'leg',next),undefined);assert.deepEqual(current(s,'leg'),[125]);
 const legacy=JSON.parse(JSON.stringify(s));delete legacy.exerciseRecords;
 const sessions=JSON.stringify(legacy.sessions),loads=JSON.stringify(legacy.history);
 migrateState(legacy);assert.equal(JSON.stringify(legacy.sessions),sessions);assert.equal(JSON.stringify(legacy.history),loads);assert.ok(exerciseRecord(legacy,w,'leg',day));
 const count=legacy.exerciseRecords.length;migrateState(legacy);assert.equal(legacy.exerciseRecords.length,count);
 complete(s,workouts[2],day);assert.ok(exerciseRecord(s,workouts[2],'cardio',day));assert.ok(exerciseRecord(s,workouts[2],'flex',day));
 undo(s,s.sessions.at(-1).id);assert.equal(exerciseRecord(s,workouts[2],'cardio',day),undefined);
});
test('interface: edição, persistência, conclusão, desfazer e gráfico',async()=>{
 const listeners={},nodes={};
 for(const id of ['#app','#message','#training-tab','#progress-tab'])nodes[id]={innerHTML:'',textContent:'',setAttribute(){},addEventListener(name,fn){listeners[name]=fn;},querySelector(){return {focus(){}};}};
 let modal;
 globalThis.document={querySelector:id=>nodes[id],getElementById:id=>nodes['#'+id],body:{append(){}},createElement(){
  const children={},events={};
  modal={innerHTML:'',setAttribute(){},addEventListener(name,fn){events[name]=fn;},querySelector(selector){return children[selector]??={textContent:'',hidden:true,focus(){},querySelector:selector=>modal.querySelector(selector)};},showModal(){this.open=true;},close(){this.open=false;events.close?.();},remove(){}};
  return modal;
 }};
 const store=new Map();globalThis.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v)};
 globalThis.window={addEventListener(){}};
 const oldInterval=globalThis.setInterval;globalThis.setInterval=()=>0;
 const oldTimeout=globalThis.setTimeout;globalThis.setTimeout=()=>0;
 try {
 await import('./app.js');
 assert.match(nodes['#app'].innerHTML,/<h1>TREINOS<\/h1>/);
 const click=dataset=>listeners.click({target:{closest:()=>({dataset,hasAttribute:()=>false})}});
 const initialDay=(workouts.find(w=>w.number===new Date().getDay())||workouts[0]).id;
 assert.match(nodes['#app'].innerHTML,new RegExp('id="day-'+initialDay+'"[^>]*aria-pressed="true"'));
 const beforeTabs=store.get('meus-treinos-v1');
 for(const w of workouts){click({day:w.id});assert.equal((nodes['#app'].innerHTML.match(/<article /g)||[]).length,1);assert.match(nodes['#app'].innerHTML,new RegExp('id="'+w.id+'"'));}
 assert.equal(store.get('meus-treinos-v1'),beforeTabs);
 click({day:'seg'});
 const segment=()=>nodes['#app'].innerHTML.match(/<article[^>]*id="seg">([\s\S]*?)<\/article>/)[1];
 click({toggle:'seg:leg'});
 assert.ok(segment().indexOf('data-exercise-row="seg:pant"')<segment().indexOf('data-exercise-row="seg:leg"'));
 assert.match(segment(),/1 de 12/);assert.match(segment(),/exercise-section">FEITOS/);
 const historyBefore=JSON.stringify(JSON.parse(store.get('meus-treinos-v1')).history);
 await import('./app.js?reload=1');click({day:'seg'});assert.match(segment(),/1 de 12/);assert.match(segment(),/DESFAZER/);
 click({toggle:'seg:leg'});assert.match(segment(),/0 de 12/);
 assert.ok(segment().indexOf('data-exercise-row="seg:leg"')<segment().indexOf('data-exercise-row="seg:pant"'));
 assert.equal(JSON.stringify(JSON.parse(store.get('meus-treinos-v1')).history),historyBefore);
 click({edit:'seg:leg'});assert.match(nodes['#app'].innerHTML,/class="editor"/);
 listeners.submit({preventDefault(){},target:{dataset:{exercise:'leg',workout:'seg'},elements:{load0:{value:'115'}}}});
 assert.equal(JSON.parse(store.get('meus-treinos-v1')).history.leg.at(-1).loads[0],115);
 click({complete:'seg'});let saved=JSON.parse(store.get('meus-treinos-v1'));assert.equal(saved.sessions.length,1);assert.match(nodes['#app'].innerHTML,/Desfazer conclusão/);
 click({undo:saved.sessions[0].id});assert.ok(JSON.parse(store.get('meus-treinos-v1')).sessions[0].undone);
 click({day:'ter'});listeners.change({target:{dataset:{choice:weekKey()+':ter:dev'},value:'1'}});click({complete:'ter'});assert.equal(JSON.parse(store.get('meus-treinos-v1')).sessions.at(-1).selections.dev,1);
 const preserved=store.get('meus-treinos-v1');const normalSet=localStorage.setItem;localStorage.setItem=()=>{throw Error('Armazenamento cheio');};click({complete:'qua'});assert.equal(store.get('meus-treinos-v1'),preserved);assert.equal(nodes['#message'].textContent,'Armazenamento cheio');localStorage.setItem=normalSet;
 nodes['#progress-tab'].onclick();assert.match(nodes['#app'].innerHTML,/<svg/);assert.doesNotMatch(nodes['#app'].innerHTML,/class="day-tabs"/);assert.match(nodes['#app'].innerHTML,/115 kg/);
 nodes['#training-tab'].onclick();
 click({day:'qui'});for(const id of workouts[3].items)click({toggle:'qui:'+id});
 assert.equal(JSON.parse(store.get('meus-treinos-v1')).sessions.filter(s=>s.workout==='qui'&&!s.undone).length,1);
 assert.match(nodes['#app'].innerHTML,/id="day-qui"[^>]*aria-pressed="true"/);assert.match(nodes['#app'].innerHTML,/10 de 10/);assert.equal((nodes['#app'].innerHTML.match(/<article /g)||[]).length,1);
 click({day:'seg'});click({day:'qui'});assert.match(nodes['#app'].innerHTML,/10 de 10/);
 click({toggle:'qui:leg'});assert.equal(JSON.parse(store.get('meus-treinos-v1')).sessions.filter(s=>s.workout==='qui'&&!s.undone).length,0);
 nodes['#progress-tab'].onclick();
 listeners.change({target:{id:'exercise-select',value:'dev'}});assert.match(nodes['#app'].innerHTML,/Máquina \/ Halter/);
 nodes['#training-tab'].onclick();click({day:'seg'});
 click({manage:'seg:ext'});assert.equal(modal.open,true);assert.match(modal.innerHTML,/EDITAR EXERCÍCIO/);
 const submitModal=(name,load,reps)=>modal.querySelector('form').onsubmit({preventDefault(){},target:{elements:{name:{value:name},load0:{value:load},reps:{value:reps}}}});
 submitModal('Extensora personalizada','80','3x12');assert.equal(modal.open,false);
 await import('./app.js?custom=edit');click({day:'seg'});
 assert.match(nodes['#app'].innerHTML,/Extensora personalizada/);assert.match(nodes['#app'].innerHTML,/3x12/);
 assert.deepEqual(JSON.parse(store.get('meus-treinos-v1')).history.ext.map(h=>h.loads[0]),[70,80]);
 click({day:'qui'});click({add:'qui'});submitModal('Hack Squat','50','4x10');
 const newId=Object.keys(JSON.parse(store.get('meus-treinos-v1')).customExercises).find(id=>id.startsWith('exercise_'));
 await import('./app.js?custom=add');
 for(const w of workouts){click({day:w.id});assert.equal(nodes['#app'].innerHTML.includes('Hack Squat'),w.id==='qui');}
 click({day:'qui'});click({toggle:'qui:'+newId});assert.match(nodes['#app'].innerHTML,new RegExp('class="row exercise-done" data-exercise-row="qui:'+newId+'"'));
 click({toggle:'qui:'+newId});assert.match(nodes['#app'].innerHTML,new RegExp('class="row " data-exercise-row="qui:'+newId+'"'));
 click({manage:'qui:'+newId});modal.querySelector('[data-delete]').onclick();
 assert.match(modal.querySelector('p').textContent,/quinta-feira/);
 modal.querySelector('[data-keep]').onclick();assert.ok(JSON.parse(store.get('meus-treinos-v1')).customWorkouts.qui.items.includes(newId));
 const beforeFailure=store.get('meus-treinos-v1');localStorage.setItem=()=>{throw Error('Sem espaço');};submitModal('Não salvar','60','2x8');
 assert.equal(modal.open,true);assert.equal(store.get('meus-treinos-v1'),beforeFailure);assert.equal(modal.querySelector('.error').textContent,'Sem espaço');localStorage.setItem=normalSet;
 modal.querySelector('[data-delete]').onclick();modal.querySelector('[data-confirm]').onclick();
 await import('./app.js?custom=delete');click({day:'qui'});assert.doesNotMatch(nodes['#app'].innerHTML,/Hack Squat/);
 click({day:'seg'});click({manage:'seg:ext'});modal.querySelector('[data-delete]').onclick();modal.querySelector('[data-confirm]').onclick();
 await import('./app.js?custom=delete-default');click({day:'seg'});assert.doesNotMatch(nodes['#app'].innerHTML,/data-manage="seg:ext"/);
 nodes['#progress-tab'].onclick();listeners.change({target:{id:'exercise-select',value:newId}});assert.match(nodes['#app'].innerHTML,/Hack Squat/);assert.match(nodes['#app'].innerHTML,/<svg/);
 const RealDate=globalThis.Date;
 try{
  for(let day=0;day<7;day++){
   const fixed=new RealDate(2026,8,20+day,12);
   globalThis.Date=class extends RealDate{constructor(...args){super(...(args.length?args:[fixed]));}static now(){return fixed.getTime();}};
   await import('./app.js?weekday='+day);
   const expected=(workouts.find(w=>w.number===day)||workouts[0]).id;
   assert.match(nodes['#app'].innerHTML,new RegExp('id="day-'+expected+'"[^>]*aria-pressed="true"'));
   click({day:'sex'});nodes['#progress-tab'].onclick();nodes['#training-tab'].onclick();
   assert.match(nodes['#app'].innerHTML,/id="day-sex"[^>]*aria-pressed="true"/);
  }
 }finally{globalThis.Date=RealDate;}
 }finally{globalThis.setInterval=oldInterval;globalThis.setTimeout=oldTimeout;}
});

test('ficha personalizada: identidade, histórico, dias, exclusão e recarga',()=>{
 let s=createState();
 saveExercise(s,'sex','dev',{name:workouts[4].names.dev,reps:workouts[4].reps,loads:[12,4]});
 assert.equal(exerciseCatalog(s).dev.renamed,false);
 assert.equal(exerciseCatalog(s).dev.name,'Desenvolvimento Máquina ou Halter');
 const original=JSON.stringify(s.history.ext);
 saveExercise(s,'seg','ext',{name:'Extensora',reps:'3x12',loads:[70]});
 assert.equal(JSON.stringify(s.history.ext),original);
 assert.equal(exerciseCatalog(s).ext.name,'Extensora');
 assert.equal(workoutPlan(s)[0].exerciseReps.ext,'3x12');
 assert.equal(workoutPlan(s)[3].exerciseReps,undefined);
 saveExercise(s,'seg','ext',{name:'Extensora',reps:'3x12',loads:[75]});
 assert.deepEqual(s.history.ext.map(h=>h.loads[0]),[70,75]);
 const id=saveExercise(s,'qui',undefined,{name:'Hack Squat',reps:'4x10',loads:[50]});
 assert.match(id,/^exercise_/);
 for(const w of workoutPlan(s))assert.equal(w.items.includes(id),w.id==='qui');
 assert.deepEqual(s.history[id].map(h=>h.loads),[[50]]);
 s=JSON.parse(JSON.stringify(s));
 assert.equal(exerciseCatalog(s).ext.name,'Extensora');
 assert.equal(workoutPlan(s)[0].exerciseReps.ext,'3x12');
 assert.ok(workoutPlan(s)[3].items.includes(id));
 const w=workoutPlan(s)[3];toggleExercise(s,w,id);
 assert.deepEqual(exerciseRecord(s,w,id).loads,[50]);
 saveExercise(s,'qui',id,{name:'Hack',reps:'3x8',loads:[55]});
 assert.deepEqual(exerciseRecord(s,w,id).loads,[50]);
 assert.deepEqual(current(s,id),[55]);
 toggleExercise(s,w,id);assert.equal(exerciseRecord(s,w,id),undefined);
 toggleExercise(s,w,id);complete(s,w);
 const records=JSON.stringify(s.exerciseRecords),sessions=JSON.stringify(s.sessions);
 deleteExercise(s,'qui',id);deleteExercise(s,'seg','ext');
 s=JSON.parse(JSON.stringify(s));
 assert.ok(!workoutPlan(s)[3].items.includes(id));
 assert.ok(!workoutPlan(s)[0].items.includes('ext'));
 assert.ok(workoutPlan(s)[3].items.includes('ext'));
 assert.equal(JSON.stringify(s.exerciseRecords),records);assert.equal(JSON.stringify(s.sessions),sessions);
 assert.deepEqual(current(s,id),[55]);
 const fresh=saveExercise(s,'qui',undefined,{name:'Hack',reps:'3x8',loads:[10]});
 assert.notEqual(fresh,id);assert.equal(exerciseRecord(s,workoutPlan(s)[3],fresh),undefined);
 assert.ok(s.sessions.at(-1).undone);
 toggleExercise(s,workoutPlan(s)[3],fresh);assert.ok(!s.sessions.at(-1).undone);
 const next=new Date();next.setDate(next.getDate()+7);
 assert.equal(exerciseRecord(s,workoutPlan(s)[3],fresh,next),undefined);
 for(const invalid of [[-1],[NaN],[Infinity],[],['10'],null])assert.throws(()=>saveExercise(s,'qui',fresh,{name:'Hack',reps:'3x8',loads:invalid}));
 for(const id of [...workoutPlan(s)[0].items])deleteExercise(s,'seg',id);
 assert.deepEqual(workoutPlan(JSON.parse(JSON.stringify(s)))[0].items,[]);
 assert.equal(workouts[0].items.length,12);
 // A conclusão anterior sem carga permanece sem carga após editar a ficha.
 toggleExercise(s,workoutPlan(s)[2],'flex');
 saveExercise(s,'qua','flex',{name:'Flexão',reps:'3x10',loads:[5]});
 complete(s,workoutPlan(s)[2]);assert.equal(s.sessions.at(-1).loads.flex,undefined);
});
